### PR TITLE
Fix makeTable when asking for one window

### PR DESCRIPTION
**Pull request by SPPearce**
A small bug fix for #7.
(The diff appears to have a bunch of whitespace changes, it is only line 161-168 and a type in line 31 that are actually changed)

### CODE REVIEW

**Review by MatthiasLienhard — APPROVED** [review]

**Comment by SPPearce** [comment]
Thanks Matthias!

**Comment by MatthiasLienhard** [comment]
I also pushed it to the bioconductor master branch, it should be available in the devel branch in about 2-3 days, and in the next release.

**Comment by MatthiasLienhard** [comment]
Thank you for the fix!

**Comment by SPPearce** [comment]
No problem, lets me remove a hacky workaround from my package that I'm getting closer to making available.

**Pull request merged**
